description = "A Hugo theme for the smol web"
features    = []
homepage    = "https://github.com/konradreiche/smol"
license     = "MIT"
licenselink = "https://github.com/konradreiche/smol/blob/main/LICENSE"
min_version = "0.65.0"
name        = "smol"
tags        = ["blog", "clean", "minimal", "personal", "simple"]

[author]
homepage = "https://konradreiche.com/"
name     = "Konrad Reiche"
